apiVersion: v1
kind: Service
metadata:
  name: service-cliente
  namespace: urbanfood
  labels:
    app: app-cliente
spec:
  ports:
  - name: service-cliente-http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: app-cliente
  type: LoadBalancer